-- Prisma fills @default(now()) on the client (Node clock). Leases, due_at and ordering are
-- compared against the database clock, so defaults must be generated by PostgreSQL.
-- statement_timestamp() (not now()) because Prisma introspects now()/CURRENT_TIMESTAMP as its own
-- client-side now() and would report permanent drift.
-- AlterTable
ALTER TABLE "audit_log" ALTER COLUMN "occurred_at" SET DEFAULT statement_timestamp();

-- AlterTable
ALTER TABLE "consumer_effects" ALTER COLUMN "due_at" SET DEFAULT statement_timestamp(),
ALTER COLUMN "created_at" SET DEFAULT statement_timestamp(),
ALTER COLUMN "updated_at" SET DEFAULT statement_timestamp();

-- AlterTable
ALTER TABLE "outbox_events" ALTER COLUMN "created_at" SET DEFAULT statement_timestamp();
